"""
DEFORMATION LIBRARY — COMPREHENSIVE VISUALIZATION
==================================================
Loads step6_continuation_library.csv and generates 5 figures:

  Figure 1  — 3D scatter cube: every valid point as a colored dot in (Xi, fb, eta) space
  Figure 2  — 3D surface slices: f_r and f_rho surfaces at fixed eta values
  Figure 3  — Combined effect heatmaps: f_r and f_rho at every eta slice
  Figure 4  — Power-law log-log analysis
  Figure 5  — f_r × f_rho joint scatter (reveals the physical coupling)

Run:
    python visualize_library.py

Requires:  numpy, pandas, matplotlib
           step6_continuation_library.csv  in the same folder
           (generated by step6_continuation.py — 630/630 valid points,
            zero excited states, path continuation used for 11 points)
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import warnings
warnings.filterwarnings('ignore')

# ── Load data ─────────────────────────────────────────────────────
df_all  = pd.read_csv('step6_continuation_library.csv')
df      = df_all[df_all['valid'] == 1].copy()

Xi_vals  = sorted(df['Xi'].unique())
fb_vals  = sorted(df['fb_core'].unique())
eta_vals = sorted(df['eta'].unique())

print(f"Loaded {len(df_all)} total points, {len(df)} valid ground-state points")
print(f"Xi  range: {df['Xi'].min():.3f} – {df['Xi'].max():.3f}")
print(f"fb  range: {df['fb_core'].min():.3f} – {df['fb_core'].max():.3f}")
print(f"eta range: {df['eta'].min():.2f} – {df['eta'].max():.2f}")


# ══════════════════════════════════════════════════════════════════
# FIGURE 1: 3D SCATTER CUBE
# ══════════════════════════════════════════════════════════════════
# Each valid grid point is plotted as a sphere in (Xi, fb, eta) space.
# Color encodes f_r:  green = core barely changed (f_r ~ 1)
#                     red   = core strongly squeezed (f_r << 1)
# Size encodes f_rho: larger dot = higher central density.
#
# What to look for:
#   - The red corner (top-right-front: large Xi, large fb, small eta)
#     is where squeezing is strongest — SMBH + concentrated baryons together.
#   - The green corner (bottom-left-back: Xi=0, fb=0, large eta) is the
#     isolated soliton region where nothing happens.
#   - Grey dots = excluded excited states (shown for reference).

fig1 = plt.figure(figsize=(14, 11))
ax = fig1.add_subplot(111, projection='3d')

norm_fr = mcolors.Normalize(vmin=0.2, vmax=1.0)
cmap_fr = plt.cm.RdYlGn

# Plot valid points — black edge makes yellow/light dots visible
sc = ax.scatter(
    df['Xi'], df['fb_core'], np.log10(df['eta']),
    c=df['f_r'], cmap=cmap_fr, norm=norm_fr,
    s=50 + 90 * (df['f_rho'] - 1) / (df['f_rho'].max() - 1),
    alpha=0.92, edgecolors='black', linewidths=0.4, zorder=5
)

# Plot excluded points if any (continuation library has zero, but kept for robustness)
df_exc = df_all[(df_all['converged'] == 1) & (df_all['valid'] == 0)]
if len(df_exc):
    ax.scatter(
        df_exc['Xi'], df_exc['fb_core'], np.log10(df_exc['eta']),
        c='#cccccc', s=20, alpha=0.4,
        edgecolors='black', linewidths=0.3, zorder=2,
        label='Excluded (excited state)'
    )

cbar = fig1.colorbar(sc, ax=ax, pad=0.1, shrink=0.6)
cbar.set_label('$f_r = r_c / r_{c0}$', fontsize=12)

ax.set_xlabel('$\\Xi$  (SMBH strength)', fontsize=11, labelpad=10)
ax.set_ylabel('$f_{b,core}$  (baryon fraction)', fontsize=11, labelpad=10)
ax.set_zlabel('$\\log_{10}(\\eta)$  (concentration)', fontsize=11, labelpad=10)
ax.set_title(
    '3D deformation library\n'
    'Colour = $f_r$ (green=intact, red=squeezed)   '
    'Size = $f_\\rho$ (larger = denser core)',
    fontsize=12, pad=15
)

eta_ticks = [0.1, 0.3, 0.5, 1.0, 2.0, 5.0]
ax.set_zticks(np.log10(eta_ticks))
ax.set_zticklabels([str(e) for e in eta_ticks])
ax.view_init(elev=20, azim=-50)
ax.legend(loc='upper left', fontsize=9)

# Annotation: strongest squeezing corner
ax.text(0.9, 0.75, np.log10(0.1), 'Maximum\nsqueezing', fontsize=9,
        color='darkred', ha='center')
ax.text(0.0, 0.0, np.log10(5.0), 'Isolated\nsoliton', fontsize=9,
        color='darkgreen', ha='center')

plt.tight_layout()


# ══════════════════════════════════════════════════════════════════
# FIGURE 2: 3D SURFACE SLICES of f_r
# ══════════════════════════════════════════════════════════════════
# Shows f_r as a surface over (Xi, fb) for three representative eta values.
# Reading this: each surface is a 2D map of how much the core shrinks
# as you increase SMBH strength (left-right) and baryon fraction (front-back).
# Three eta slices show how baryon concentration modifies the surface shape.

eta_plot = [0.3, 1.0, 5.0]   # compact, moderate, extended
eta_labels = ['η=0.3 (compact baryons)', 'η=1.0 (moderate)', 'η=5.0 (extended)']
colors_surf = ['#e84545', '#f5a623', '#2d9cdb']

fig2, axes2 = plt.subplots(1, 3, figsize=(18, 6),
                            subplot_kw={'projection': '3d'})
fig2.suptitle('$f_r$ surface over (Ξ, $f_{b,core}$) at three baryon concentrations',
              fontsize=13, y=1.01)

Xi_arr  = np.array(Xi_vals)
fb_arr  = np.array(fb_vals)
Xi_mesh, fb_mesh = np.meshgrid(Xi_arr, fb_arr, indexing='ij')

for ax2, eta, lab, col in zip(axes2, eta_plot, eta_labels, colors_surf):
    fr_mat  = np.full_like(Xi_mesh, np.nan, dtype=float)
    frho_mat = np.full_like(Xi_mesh, np.nan, dtype=float)

    for i, Xi in enumerate(Xi_vals):
        for j, fb in enumerate(fb_vals):
            row = df[(df['Xi']==Xi) & (df['fb_core']==fb) & (df['eta']==eta)]
            if len(row):
                fr_mat[i,j]   = row['f_r'].values[0]
                frho_mat[i,j] = row['f_rho'].values[0]

    # Only plot where we have valid data
    mask = ~np.isnan(fr_mat)
    if mask.sum() > 3:
        ax2.plot_surface(Xi_mesh, fb_mesh, fr_mat,
                         cmap='RdYlGn', vmin=0.2, vmax=1.0,
                         alpha=0.85, linewidth=0.3, edgecolor='gray')

    ax2.set_xlabel('$\\Xi$', fontsize=10, labelpad=6)
    ax2.set_ylabel('$f_{b,core}$', fontsize=10, labelpad=6)
    ax2.set_zlabel('$f_r$', fontsize=10, labelpad=6)
    ax2.set_zlim(0.1, 1.05)
    ax2.set_title(lab, fontsize=11)
    ax2.view_init(elev=25, azim=-60)

plt.tight_layout()


# ══════════════════════════════════════════════════════════════════
# FIGURE 3: HEATMAP GRID — f_r and f_rho at every eta slice
# ══════════════════════════════════════════════════════════════════
# 7 columns (one per eta value) × 2 rows (f_r top, f_rho bottom).
# Each cell is a heatmap over (Xi × fb).
# Reading this: scan left→right = increasing baryon concentration (decreasing eta
# means more concentrated). Scan top→bottom = f_r (how much core shrinks)
# vs f_rho (how much core densifies). White cells = excluded/failed.

n_eta = len(eta_vals)

# Reserve extra column on the right for each colorbar
fig3, axes3 = plt.subplots(2, n_eta + 1, figsize=(22, 7),
                            gridspec_kw={'width_ratios': [1]*n_eta + [0.08],
                                         'wspace': 0.35, 'hspace': 0.4})
fig3.suptitle('$f_r$ (top) and $f_\\rho$ (bottom) heatmaps at each η value',
              fontsize=13, y=1.02)

norm_fr2   = mcolors.Normalize(vmin=0.2,  vmax=1.0)
norm_frho2 = mcolors.Normalize(vmin=1.0,  vmax=10.0)
cmap_fr2   = plt.cm.RdYlGn
cmap_frho2 = plt.cm.YlOrRd

for ie, eta in enumerate(eta_vals):
    fr_mat   = np.full((len(Xi_vals), len(fb_vals)), np.nan)
    frho_mat = np.full((len(Xi_vals), len(fb_vals)), np.nan)

    for i, Xi in enumerate(Xi_vals):
        for j, fb in enumerate(fb_vals):
            row = df[(df['Xi']==Xi) & (df['fb_core']==fb) & (df['eta']==eta)]
            if len(row):
                fr_mat[i,j]   = row['f_r'].values[0]
                frho_mat[i,j] = row['f_rho'].values[0]

    # f_r heatmap (top row)
    ax = axes3[0, ie]
    ax.imshow(fr_mat.T, origin='lower', aspect='auto',
              norm=norm_fr2, cmap=cmap_fr2,
              extent=[Xi_vals[0], Xi_vals[-1], fb_vals[0], fb_vals[-1]])
    ax.set_title(f'η = {eta}', fontsize=10)
    if ie == 0:
        ax.set_ylabel('$f_{b,core}$', fontsize=9)
    else:
        ax.set_yticklabels([])
    ax.set_xlabel('$\\Xi$', fontsize=9)
    ax.tick_params(labelsize=7)

    # f_rho heatmap (bottom row)
    ax = axes3[1, ie]
    ax.imshow(frho_mat.T, origin='lower', aspect='auto',
              norm=norm_frho2, cmap=cmap_frho2,
              extent=[Xi_vals[0], Xi_vals[-1], fb_vals[0], fb_vals[-1]])
    if ie == 0:
        ax.set_ylabel('$f_{b,core}$', fontsize=9)
    else:
        ax.set_yticklabels([])
    ax.set_xlabel('$\\Xi$', fontsize=9)
    ax.tick_params(labelsize=7)

# Colorbars in the dedicated rightmost column
cax_fr   = axes3[0, n_eta]
cax_frho = axes3[1, n_eta]
fig3.colorbar(cm.ScalarMappable(norm=norm_fr2,   cmap=cmap_fr2),
              cax=cax_fr,   label='$f_r$')
fig3.colorbar(cm.ScalarMappable(norm=norm_frho2, cmap=cmap_frho2),
              cax=cax_frho, label='$f_\\rho$')


# ══════════════════════════════════════════════════════════════════
# FIGURE 4: LOG-LOG POWER-LAW ANALYSIS
# ══════════════════════════════════════════════════════════════════
# Checks whether f_r and f_rho follow power laws in Xi and fb.
# A straight line in log-log space means f ~ X^alpha.
# The slope tells you the power-law exponent.
# Compare the SMBH slope to the Bar+2018 theoretical limit of -0.5.

fig4, axes4 = plt.subplots(2, 2, figsize=(14, 10))
fig4.suptitle('Log-log power-law analysis', fontsize=13)

colors_eta_4 = plt.cm.plasma(np.linspace(0.1, 0.9, len(eta_vals)))
colors_fb_4  = plt.cm.viridis(np.linspace(0.1, 0.9, len(fb_vals)))

# f_r vs Xi (fb=0, each eta)
ax = axes4[0,0]
for ie, eta in enumerate(eta_vals):
    sub = df[(df['fb_core']==0.0) & (df['eta']==eta) & (df['Xi']>0)]
    if len(sub) > 2:
        ax.loglog(sub['Xi'], sub['f_r'], 'o-', color=colors_eta_4[ie],
                  ms=5, lw=1.5, label=f'η={eta}')
# Bar+2018 reference slope -0.5
x_ref = np.array([0.01, 1.0])
ax.loglog(x_ref, 0.95 * x_ref**(-0.5), 'k--', lw=1.5, alpha=0.5,
          label='slope $-0.5$ (Bar+2018 limit)')
ax.set_xlabel('$\\Xi$', fontsize=11); ax.set_ylabel('$f_r$', fontsize=11)
ax.set_title('$f_r$ vs $\\Xi$  (fb=0)', fontsize=11)
ax.legend(fontsize=7, ncol=2); ax.grid(alpha=0.3, which='both')

# f_rho vs Xi (fb=0, each eta)
ax = axes4[0,1]
for ie, eta in enumerate(eta_vals):
    sub = df[(df['fb_core']==0.0) & (df['eta']==eta) & (df['Xi']>0)]
    if len(sub) > 2:
        ax.loglog(sub['Xi'], sub['f_rho'], 's-', color=colors_eta_4[ie],
                  ms=5, lw=1.5, label=f'η={eta}')
ax.set_xlabel('$\\Xi$', fontsize=11); ax.set_ylabel('$f_\\rho$', fontsize=11)
ax.set_title('$f_\\rho$ vs $\\Xi$  (fb=0)', fontsize=11)
ax.legend(fontsize=7, ncol=2); ax.grid(alpha=0.3, which='both')

# f_r vs fb (Xi=0, each eta)
ax = axes4[1,0]
for ie, eta in enumerate(eta_vals):
    sub = df[(df['Xi']==0.0) & (df['eta']==eta) & (df['fb_core']>0)]
    if len(sub) > 2:
        ax.loglog(sub['fb_core'], sub['f_r'], 'o-', color=colors_eta_4[ie],
                  ms=5, lw=1.5, label=f'η={eta}')
ax.set_xlabel('$f_{b,core}$', fontsize=11); ax.set_ylabel('$f_r$', fontsize=11)
ax.set_title('$f_r$ vs $f_{b,core}$  (Ξ=0)', fontsize=11)
ax.legend(fontsize=7, ncol=2); ax.grid(alpha=0.3, which='both')

# Measure power-law slopes
ax2 = axes4[1,1]
ax2.set_title('Measured power-law slopes', fontsize=11)
slopes_Xi  = []
slopes_fb  = []
eta_labs   = []

for eta in eta_vals:
    sub_Xi = df[(df['fb_core']==0.0) & (df['eta']==eta) & (df['Xi']>0.02)]
    sub_fb = df[(df['Xi']==0.0)      & (df['eta']==eta) & (df['fb_core']>0.02)]
    if len(sub_Xi) >= 3:
        s, _ = np.polyfit(np.log(sub_Xi['Xi']), np.log(sub_Xi['f_r']), 1)
        slopes_Xi.append(s)
    else:
        slopes_Xi.append(np.nan)
    if len(sub_fb) >= 3:
        s, _ = np.polyfit(np.log(sub_fb['fb_core']), np.log(sub_fb['f_r']), 1)
        slopes_fb.append(s)
    else:
        slopes_fb.append(np.nan)
    eta_labs.append(eta)

x_pos = np.arange(len(eta_labs))
w = 0.35
ax2.bar(x_pos - w/2, slopes_Xi, w, label='slope vs $\\Xi$',  color='#e84545', alpha=0.8)
ax2.bar(x_pos + w/2, slopes_fb, w, label='slope vs $f_b$', color='#2d9cdb', alpha=0.8)
ax2.axhline(-0.5, ls='--', color='black', alpha=0.5, lw=1.5, label='Bar+2018 limit (−0.5)')
ax2.axhline(0.0,  ls='-',  color='gray',  alpha=0.3, lw=0.8)
ax2.set_xticks(x_pos); ax2.set_xticklabels([f'η={e}' for e in eta_labs], fontsize=8)
ax2.set_ylabel('Power-law slope of $f_r$', fontsize=11)
ax2.legend(fontsize=9); ax2.grid(alpha=0.3, axis='y')

plt.tight_layout()


# ══════════════════════════════════════════════════════════════════
# FIGURE 5: f_r × f_rho JOINT SCATTER — the physical coupling
# ══════════════════════════════════════════════════════════════════
# Every valid point plotted as (f_r, f_rho).
# Physical prediction for a uniform-density sphere at fixed mass:
#   rho * r^3 = const  →  f_rho = f_r^(-3)
# A real soliton is not uniform, so the actual curve differs,
# but the trend should still be f_rho ~ f_r^alpha with alpha < 0.
# Color = Xi, shape = fb category.
# Reading: points falling near the power-law curve confirm physical consistency.
# Points far off the curve would indicate solver errors.

fig5, ax5 = plt.subplots(figsize=(10, 8))
norm_Xi = mcolors.Normalize(vmin=0.0, vmax=1.0)
cmap_Xi = plt.cm.plasma

sc5 = ax5.scatter(df['f_r'], df['f_rho'],
                  c=df['Xi'], cmap=cmap_Xi, norm=norm_Xi,
                  s=25, alpha=0.8, edgecolors='black', linewidths=0.4)

# Theoretical uniform-sphere line: f_rho = f_r^(-3)
fr_line = np.linspace(0.2, 1.05, 200)
ax5.plot(fr_line, fr_line**(-3), 'k--', lw=1.5, alpha=0.5,
         label='Uniform sphere: $f_\\rho = f_r^{-3}$')

# Fit actual power law to the data
mask_fit = (df['f_r'] > 0.2) & (df['f_r'] < 1.0) & (df['f_rho'] > 1.0)
if mask_fit.sum() > 10:
    slope_j, intercept_j = np.polyfit(
        np.log(df.loc[mask_fit,'f_r']),
        np.log(df.loc[mask_fit,'f_rho']), 1)
    ax5.plot(fr_line, np.exp(intercept_j) * fr_line**slope_j,
             'r-', lw=2, alpha=0.8,
             label=f'Fitted: $f_\\rho \\propto f_r^{{{slope_j:.2f}}}$')

cbar5 = fig5.colorbar(sc5, ax=ax5, pad=0.02)
cbar5.set_label('$\\Xi$ (SMBH strength)', fontsize=11)

ax5.set_xlabel('$f_r = r_c / r_{c0}$  (core radius ratio)', fontsize=12)
ax5.set_ylabel('$f_\\rho = \\rho_c / \\rho_{c0}$  (central density ratio)', fontsize=12)
ax5.set_title(
'',
    fontsize=12)
ax5.legend(fontsize=10)
ax5.set_yscale('log'); ax5.set_xscale('log')
ax5.grid(alpha=0.3, which='both')

plt.tight_layout()


# ── Show all figures ───────────────────────────────────────────────
print("\nDisplaying all figures...")
print("  Figure 1: 3D scatter cube")
print("  Figure 2: 3D surface slices")
print("  Figure 3: Heatmap grid (all eta values)")
print("  Figure 4: Log-log power-law analysis")
print("  Figure 5: f_r × f_rho coupling scatter")
plt.show()